import './App.css';
import Card from './components/Card';
import { Button } from './components/Button';
import { useState } from 'react';

function App() {
	const [uiTab, setUiTab] = useState('Please Select a Tab');

	const selectHandler = (e) => {
		setUiTab(e);
	};

	return (
		<>
			<menu>
				<Button label={'React'} onSelect={() => selectHandler('React')} />
				<Button label={'NodeJs'} onSelect={() => selectHandler('NodeJs')} />
				<Button
					label={'React Native'}
					onSelect={() => selectHandler('React Native')}
				/>
			</menu>
			<p>{uiTab}</p>
			<Card
				title={'AI Generated Card'}
				content={'This Card was generated by AI'}
			/>
		</>
	);
}

export default App;
